import localFont from "next/font/local";
import "./globals.css";
import "antd/dist/reset.css"; // ✅ required for Ant Design
import Layout from "antd/es/layout/layout";
import Header from "./component/Header";
import Footer from "./component/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header>
        <Header/>
      </header>
        <Layout>
          {children}
        </Layout>
        <footer>
          <Footer/>
        </footer>
        
        
      </body>
    </html>
  );
}
